/* tslint:disable */
/* eslint-disable */
/**
 * IONOS DBaaS REST API
 * An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Details about the network connection for your cluster.
 * @export
 * @interface Connection
 */
export interface Connection {
    /**
     * The datacenter to connect your cluster to.
     * @type {string}
     * @memberof Connection
     */
    datacenterId: string;
    /**
     * The numeric LAN ID to connect your cluster to.
     * @type {string}
     * @memberof Connection
     */
    lanId: string;
    /**
     * The IP and subnet for your cluster. Note the following unavailable IP ranges: 10.233.64.0/18 10.233.0.0/18 10.233.114.0/24 
     * @type {string}
     * @memberof Connection
     */
    cidr: string;
}


