/* tslint:disable */
/* eslint-disable */
/**
 * IONOS DBaaS PostgreSQL REST API
 * An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional PostgreSQL database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {

    /**
     * The URN of an IAM user.
     * @type {string}
     * @memberof Metadata
     */
    createdBy?: string;

    /**
     * The ID of an IAM user.
     * @type {string}
     * @memberof Metadata
     */
    createdByUserId?: string;

    /**
     * An ISO 8601 timestamp.
     * @type {string}
     * @memberof Metadata
     */
    createdDate?: string;

    /**
     * The URN of an IAM user.
     * @type {string}
     * @memberof Metadata
     */
    lastModifiedBy?: string;

    /**
     * The ID of an IAM user.
     * @type {string}
     * @memberof Metadata
     */
    lastModifiedByUserId?: string;

    /**
     * An ISO 8601 timestamp.
     * @type {string}
     * @memberof Metadata
     */
    lastModifiedDate?: string;

    /**
     * The URN of the resource.
     * @type {string}
     * @memberof Metadata
     */
    resourceURN?: string;
}


